### ISSUE TITLE
about code!

### ISSUE THREAD

**Issue by pswena** [haochenheheda/NFormer#5]
I have some questions about your code. In your paper, The batch size is set to 128 for training the Resnet-50 feature extractor and is set to 2048 for training NFormer. But in your code, the batch size is 64 for Resnet-50 and 2 for NFormer.

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  NFORMER_MAX_EPOCHS: 20
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

![image](https://user-images.githubusercontent.com/44701958/181403255-e85a4458-8143-4bea-8342-ea187546a532.png)

And another question in your code is that the function evaluator is same as function nfomer_evalutor. 
![image](https://user-images.githubusercontent.com/44701958/181403616-72f99c44-d2ed-4b13-a3ff-12b0a813e439.png)

**Comment by haochenheheda** [comment]
1. the hyperparameters in this repo are not exactly the same as in the paper. You can change the 64 to 128 for the feature extractor. As for the batch size of NFormer in the paper, it means the sequence length instead of the mini-batch size. Sorry for my inaccurate description！
2. evaluator is not same as nfomer_evalutor. evaluator uses func 'R1_mAP', while nfomer_evalutor uses func 'NFormer_R1_mAP'

**Comment by pswena** [comment]
> 1. the hyperparameters in this repo are not exactly the same as in the paper. You can change the 64 to 128 for the feature extractor. As for the batch size of NFormer in the paper, it means the sequence length instead of the mini-batch size. Sorry for my inaccurate description！
> 2. evaluator is not same as nfomer_evalutor. evaluator uses func 'R1_mAP', while nfomer_evalutor uses func 'NFormer_R1_mAP'

Thanks for your quickly reply! But the batch size of NFormer is the sequence length.  Is it the data_length in your code in the following picture?
![image](https://user-images.githubusercontent.com/44701958/181467712-58e047c2-8d88-4594-9241-555c3047ba72.png)

**Comment by haochenheheda** [comment]
Right.

**Comment by pswena** [comment]
> Right.

Thank you very much ! I have no questions.

**Comment by InstantWindy** [comment]
> > 1. the hyperparameters in this repo are not exactly the same as in the paper. You can change the 64 to 128 for the feature extractor. As for the batch size of NFormer in the paper, it means the sequence length instead of the mini-batch size. Sorry for my inaccurate description！
> > 2. evaluator is not same as nfomer_evalutor. evaluator uses func 'R1_mAP', while nfomer_evalutor uses func 'NFormer_R1_mAP'
> 
> Thanks for your quickly reply! But the batch size of NFormer is the sequence length. Is it the data_length in your code in the following picture? ![image](https://user-images.githubusercontent.com/44701958/181467712-58e047c2-8d88-4594-9241-555c3047ba72.png)

but in the code, ' nformer_dataset = NFormerDataset(data_generator.state.metrics['data'])' , No parameters were passed, so data_length is still 7000.
